export type AssetType = 'crypto' | 'stock' | 'etf' | 'index' | 'commodity' | 'fx' | 'macro';
export interface Asset { symbol: string; label: string; type: AssetType; }
export interface AssetCategory { id: string; name: string; assets: Asset[]; }
export interface WatchlistResponse { categories: AssetCategory[]; }
export interface AssetSearchItem { symbol: string; label: string; thai_name?: string; asset_type: string; market: string; keywords?: string; alias?: string; sector?: string; industry?: string; country?: string; currency?: string; exchange?: string; }
export interface AssetSearchResponse { query: string; count: number; assets: AssetSearchItem[]; source: string; }
export interface SectorItem { name: string; count: number; assets: AssetSearchItem[]; }
export interface SectorResponse { sectors: SectorItem[]; source: string; limitations?: string[]; }
export interface ResponseMetadata { provider: string; source: string; updated_at: string; cache_age_seconds: number; cache_status: string; confidence: 'high' | 'medium' | 'low' | string; status: string; latency_ms: number; warnings?: string[]; data_warning?: string; }
export interface HistoryPoint { time: string; open: number | null; high: number | null; low: number | null; close: number | null; volume: number | null; }
export interface AssetQuote { symbol: string; name: string; asset_type: string; currency: string; price: number | null; previous_close: number | null; change: number | null; change_percent: number | null; open: number | null; high: number | null; low: number | null; volume: number | null; market_cap: number | null; trailing_pe?: number | null; price_to_book?: number | null; price_to_sales?: number | null; trailing_eps?: number | null; earnings_growth?: number | null; revenue_growth?: number | null; debt_to_equity?: number | null; return_on_equity?: number | null; return_on_assets?: number | null; return_on_invested_capital?: number | null; beta?: number | null; sector?: string | null; industry?: string | null; exchange?: string | null; country?: string | null; logo_url?: string | null; source: string; timestamp: string; metadata?: ResponseMetadata; data_warning?: string; error?: string; }
export interface AssetHistory { symbol: string; range: string; interval: string; points: HistoryPoint[]; source: string; metadata?: ResponseMetadata; data_warning?: string; error?: string; }
export interface TechnicalResponse { symbol: string; status: string; available_indicators: string[]; indicators: Record<string, unknown>; series: Array<Record<string, string | number | null>>; interpretation?: { trend: string; evidence: string[]; confidence: string; limitations: string[] }; source: string; message?: string; message_th?: string; disclaimer: string; }
export interface AnalysisResponse { symbol: string; trend: string; facts: string[]; interpretation: string[]; bullish_factors: string[]; bearish_factors: string[]; risks: string[]; risk_score: number | null; volatility_level: string; support_resistance: { support: string; resistance: string }; invalidation: string; cautious_action_plan: string[]; disclaimer: string; metadata?: ResponseMetadata; }
export interface RiskResponse { symbol: string; asset_type: string; risk_score: number | null; volatility_level: string; main_risks: string[]; risk_controls: string[]; facts: string[]; interpretation: string; categories?: Array<{ category: string; score: number; probability: string; severity: string; trend?: string; evidence: string; mitigation: string }>; disclaimer: string; metadata?: ResponseMetadata; }
export interface FinancialsResponse { symbol: string; applicable: boolean; status?: string; message?: string; message_th?: string; facts?: Record<string, string | number | null>; interpretation?: Record<string, string | null>; risks?: string[]; cautious_action_plan?: string[]; alternative_fundamentals?: { asset_type: string; focus_areas: string[] }; disclaimer: string; metadata?: ResponseMetadata; }
export interface CompareItem { symbol: string; name: string; asset_type: string; price: number | null; change_percent: number | null; performance_1d_percent?: number | null; performance_1w_percent?: number | null; performance_1mo_percent?: number | null; performance_ytd_percent?: number | null; realized_volatility_percent?: number | null; max_drawdown_percent?: number | null; trend?: string; market_cap?: number | null; pe?: number | null; pb?: number | null; ps?: number | null; eps_growth?: number | null; revenue_growth?: number | null; debt?: number | null; roe?: number | null; roa?: number | null; roic?: number | null; beta?: number | null; dividend_yield?: number | null; sector?: string | null; correlation_to_first?: number | null; relative_strength?: number | null; ai_opinion?: string; investment_thesis?: { summary: string; evidence: string[]; confidence: string; limitations: string[] }; currency: string; volatility_estimate: string; risk_score: number | null; source: string; timestamp?: string; error?: string; }
export interface CompareResponse { symbols: string[]; items: CompareItem[]; performance_points: Array<Record<string, string | number | null>>; correlation_matrix?: Array<Record<string, string | number | null>>; radar_chart?: Array<Record<string, string | number | null>>; summary: { th: string; en: string }; disclaimer: string; }
export interface AssistantResponse { answer: string; facts_used: string[]; risks: string[]; follow_up_questions: string[]; disclaimer: string; recommendation?: string; confidence?: string; missing_data?: string[]; }
export interface CalendarEvent { date: string; name: string; region: string; impact_level: string; related_assets: string[]; note_th: string; note_en: string; }
export interface CalendarResponse { events: CalendarEvent[]; source: string; provider_configured?: boolean; message?: string; message_th?: string; }
export interface NewsImpactItem { headline: string; source: string; url?: string | null; published_at?: string | null; asset_impact: string; impact_level: string; sentiment: string; ai_explanation: string; risk_warning: string; }
export interface NewsImpactResponse { symbol: string; source: string; provider_roadmap: string[]; items: NewsImpactItem[]; disclaimer: string; provider_configured?: boolean; message?: string; message_th?: string; error?: string; }
export interface SentimentResponse { symbol: string; score: number | null; label: string; source: string; note: string; note_th?: string; provider_configured?: boolean; }
export interface PortfolioTransaction { symbol: string; side: 'buy' | 'sell'; quantity: number; price: number; date: string; }
export interface PortfolioHolding { symbol: string; quantity: number; averageCost: number; currency: string; cashBalance?: number; transactions?: PortfolioTransaction[]; }
export interface QuotesResponse { symbols: string[]; items: AssetQuote[]; source: string; }
export interface PortfolioEvaluationItem { symbol: string; quantity: number; average_cost: number; last_price: number | null; currency: string; market_value: number | null; cost_basis: number; gain_loss: number | null; gain_loss_percent: number | null; allocation_percent: number | null; sector?: string | null; asset_type?: string | null; source: string; timestamp?: string; error?: string; }
export interface PortfolioEvaluationResponse { items: PortfolioEvaluationItem[]; cash_balance?: number; total_equity?: number | null; total_value: number | null; total_cost: number | null; total_gain_loss: number | null; total_gain_loss_percent: number | null; realized_gain_loss?: number; daily_return_percent?: number | null; portfolio_return_percent?: number | null; risk_score?: number | null; diversification_score?: number | null; sector_allocation?: Array<{ sector: string; allocation_percent: number }>; sharpe_ratio?: number | null; max_drawdown_percent?: number | null; performance_points?: Array<Record<string, string | number | null>>; transaction_history?: Array<Record<string, string | number | null>>; transaction_count?: number; analytics_status?: string; analytics_unavailable_reason?: string; currency_conversion?: string; source: string; disclaimer: string; }
