export type AssetType = 'crypto' | 'stock' | 'index' | 'commodity' | 'fx' | 'macro';
export interface Asset { symbol: string; label: string; type: AssetType; }
export interface AssetCategory { id: string; name: string; assets: Asset[]; }
export interface WatchlistResponse { categories: AssetCategory[]; }
export interface ResponseMetadata { provider: string; source: string; updated_at: string; cache_age_seconds: number; cache_status: string; confidence: 'high' | 'medium' | 'low' | string; status: string; latency_ms: number; warnings?: string[]; data_warning?: string; }
export interface HistoryPoint { time: string; open: number | null; high: number | null; low: number | null; close: number | null; volume: number | null; }
export interface AssetQuote { symbol: string; name: string; asset_type: string; currency: string; price: number | null; previous_close: number | null; change: number | null; change_percent: number | null; open: number | null; high: number | null; low: number | null; volume: number | null; market_cap: number | null; source: string; timestamp: string; metadata?: ResponseMetadata; data_warning?: string; error?: string; }
export interface AssetHistory { symbol: string; range: string; interval: string; points: HistoryPoint[]; source: string; metadata?: ResponseMetadata; data_warning?: string; error?: string; }
export interface AnalysisResponse { symbol: string; trend: string; facts: string[]; interpretation: string[]; bullish_factors: string[]; bearish_factors: string[]; risks: string[]; risk_score: number | null; volatility_level: string; support_resistance: { support: string; resistance: string }; invalidation: string; cautious_action_plan: string[]; disclaimer: string; metadata?: ResponseMetadata; }
export interface RiskResponse { symbol: string; asset_type: string; risk_score: number | null; volatility_level: string; main_risks: string[]; risk_controls: string[]; facts: string[]; interpretation: string; disclaimer: string; metadata?: ResponseMetadata; }
export interface FinancialsResponse { symbol: string; applicable: boolean; status?: string; message?: string; message_th?: string; facts?: Record<string, string | number | null>; interpretation?: Record<string, string | null>; risks?: string[]; cautious_action_plan?: string[]; alternative_fundamentals?: { asset_type: string; focus_areas: string[] }; disclaimer: string; metadata?: ResponseMetadata; }
export interface CompareItem { symbol: string; name: string; asset_type: string; price: number | null; change_percent: number | null; currency: string; volatility_estimate: string; risk_score: number | null; source: string; timestamp?: string; error?: string; }
export interface CompareResponse { symbols: string[]; items: CompareItem[]; performance_points: Array<Record<string, string | number | null>>; summary: { th: string; en: string }; disclaimer: string; }
export interface AssistantResponse { answer: string; facts_used: string[]; risks: string[]; follow_up_questions: string[]; disclaimer: string; }
export interface CalendarEvent { date: string; name: string; region: string; impact_level: string; related_assets: string[]; note_th: string; note_en: string; }
export interface CalendarResponse { events: CalendarEvent[]; source: string; provider_configured?: boolean; message?: string; message_th?: string; }
export interface NewsImpactItem { headline: string; source: string; asset_impact: string; impact_level: string; sentiment: string; ai_explanation: string; risk_warning: string; }
export interface NewsImpactResponse { symbol: string; source: string; provider_roadmap: string[]; items: NewsImpactItem[]; disclaimer: string; provider_configured?: boolean; message?: string; message_th?: string; error?: string; }
export interface SentimentResponse { symbol: string; score: number | null; label: string; source: string; note: string; note_th?: string; provider_configured?: boolean; }
export interface PortfolioHolding { symbol: string; quantity: number; averageCost: number; currency: string; }
