import React from 'react';
import ReactDOM from 'react-dom/client';
import { Activity, AlertTriangle, BarChart3, Brain, BriefcaseBusiness, Building2, CalendarDays, ChevronDown, Clock3, Globe2, Info, Languages, LineChart, Newspaper, Radar, Scale, ShieldCheck, Sparkles, WalletCards, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Line, LineChart as ReLineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from './lib/api';
import { DEFAULT_LANGUAGE, translations, type Language, type Translation } from './i18n';
import type { AnalysisResponse, Asset, AssetCategory, AssetHistory, AssetQuote, CalendarResponse, CompareResponse, FinancialsResponse, NewsImpactResponse, PortfolioHolding, RiskResponse, SentimentResponse } from './types/market';
import './styles.css';

const repoUrl = 'https://github.com/ponrats-ui/market-pulse-ai';
const languageKey = 'market-pulse-language';
const portfolioKey = 'market-pulse-portfolio';
const ranges = ['1d', '5d', '1mo', '3mo', '6mo', '1y', '5y'];
const comparePresets = [['BTC-USD', 'ETH-USD'], ['NVDA', 'AMD'], ['AAPL', 'MSFT'], ['GC=F', 'SI=F'], ['CL=F', 'BZ=F'], ['^SET.BK', '^GSPC']];
const formatNumber = (value: number | null | undefined, digits = 2) => value == null ? 'N/A' : new Intl.NumberFormat('en-US', { maximumFractionDigits: digits }).format(value);
const formatPercent = (value: number | null | undefined) => value == null ? 'N/A' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}%`;
const formatTime = (value: string | undefined) => value ? new Date(value).toLocaleString() : 'N/A';
const labels = {
  th: { dashboard: 'Dashboard', compare: 'เปรียบเทียบ', assistant: 'AI Assistant', portfolio: 'พอร์ตลงทุน', calendar: 'ปฏิทินเศรษฐกิจ', news: 'News Impact', timeframe: 'ช่วงเวลา', ohlc: 'OHLC', indicators: 'ตัวชี้วัด', comparison: 'เปรียบเทียบสินทรัพย์', normalized: 'ผลตอบแทนเทียบฐาน (%)', ask: 'ถาม AI', question: 'คำถาม', holdings: 'รายการถือครอง', addHolding: 'เพิ่มสินทรัพย์', quantity: 'จำนวน', averageCost: 'ต้นทุนเฉลี่ย', currentValue: 'มูลค่าปัจจุบัน', gainLoss: 'กำไร/ขาดทุน', allocation: 'สัดส่วน', concentration: 'ความเสี่ยงกระจุกตัว', aiComment: 'ความเห็น AI', realData: 'ใช้ข้อมูลราคาจริงเมื่อเชื่อมต่อ backend', unavailableNote: 'ยังไม่มีข้อมูลจริงจากผู้ให้บริการที่ตั้งค่าไว้', impact: 'ผลกระทบ', sentiment: 'Sentiment', riskWarning: 'คำเตือนความเสี่ยง', confidence: 'ความน่าเชื่อถือ', cache: 'แคช', latency: 'เวลาโหลด', noData: 'ยังไม่มีข้อมูลสำหรับส่วนนี้', discrepancy: 'พบความคลาดเคลื่อนของข้อมูล', sourceInfo: 'ข้อมูลแหล่งที่มา' },
  en: { dashboard: 'Dashboard', compare: 'Compare', assistant: 'AI Assistant', portfolio: 'Portfolio', calendar: 'Economic Calendar', news: 'News Impact', timeframe: 'Timeframe', ohlc: 'OHLC', indicators: 'Indicators', comparison: 'Asset Comparison', normalized: 'Normalized performance (%)', ask: 'Ask AI', question: 'Question', holdings: 'Holdings', addHolding: 'Add Holding', quantity: 'Quantity', averageCost: 'Average Cost', currentValue: 'Current Value', gainLoss: 'Gain/Loss', allocation: 'Allocation', concentration: 'Concentration Risk', aiComment: 'AI Comment', realData: 'Uses real price data when backend is connected', unavailableNote: 'Real provider data is unavailable for this section', impact: 'Impact', sentiment: 'Sentiment', riskWarning: 'Risk Warning', confidence: 'Confidence', cache: 'Cache', latency: 'Latency', noData: 'No data available for this section yet', discrepancy: 'Data discrepancy detected', sourceInfo: 'Source Information' },
};

type Section = 'dashboard' | 'compare' | 'assistant' | 'portfolio' | 'calendar' | 'news';
function initialLanguage(): Language { const saved = localStorage.getItem(languageKey); return saved === 'en' || saved === 'th' ? saved : DEFAULT_LANGUAGE; }
function readPortfolio(): PortfolioHolding[] { try { return JSON.parse(localStorage.getItem(portfolioKey) ?? '[]'); } catch { return []; } }

function App() {
  const [language, setLanguage] = React.useState<Language>(initialLanguage);
  const t = translations[language];
  const l = labels[language];
  const [section, setSection] = React.useState<Section>('dashboard');
  const [categories, setCategories] = React.useState<AssetCategory[]>([]);
  const [categoryId, setCategoryId] = React.useState('crypto');
  const [assetSymbol, setAssetSymbol] = React.useState('BTC-USD');
  const [range, setRange] = React.useState('1mo');
  const [quote, setQuote] = React.useState<AssetQuote | null>(null);
  const [history, setHistory] = React.useState<AssetHistory | null>(null);
  const [analysis, setAnalysis] = React.useState<AnalysisResponse | null>(null);
  const [risk, setRisk] = React.useState<RiskResponse | null>(null);
  const [financials, setFinancials] = React.useState<FinancialsResponse | null>(null);
  const [sentiment, setSentiment] = React.useState<SentimentResponse | null>(null);
  const [compareSymbols, setCompareSymbols] = React.useState(comparePresets[0]);
  const [compare, setCompare] = React.useState<CompareResponse | null>(null);
  const [question, setQuestion] = React.useState(language === 'th' ? 'BTC ตอนนี้เสี่ยงไหม' : 'Is BTC risky right now?');
  const [answer, setAnswer] = React.useState('');
  const [portfolio, setPortfolio] = React.useState<PortfolioHolding[]>(readPortfolio);
  const [newHolding, setNewHolding] = React.useState<PortfolioHolding>({ symbol: 'BTC-USD', quantity: 0.1, averageCost: 50000, currency: 'USD' });
  const [calendar, setCalendar] = React.useState<CalendarResponse | null>(null);
  const [news, setNews] = React.useState<NewsImpactResponse | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [aboutOpen, setAboutOpen] = React.useState(false);

  React.useEffect(() => { localStorage.setItem(languageKey, language); }, [language]);
  React.useEffect(() => { localStorage.setItem(portfolioKey, JSON.stringify(portfolio)); }, [portfolio]);
  React.useEffect(() => { api.watchlist().then((data) => { setCategories(data.categories); const first = data.categories[0]; if (first) { setCategoryId(first.id); setAssetSymbol(first.assets[0]?.symbol ?? 'BTC-USD'); } }).catch((error) => console.error('Failed to load watchlist', error)); api.calendar().then(setCalendar).catch((error) => console.error('Failed to load calendar', error)); }, []);
  React.useEffect(() => { let ok = true; setLoading(true); Promise.allSettled([api.quote(assetSymbol), api.history(assetSymbol, range, range === '1d' ? '1h' : '1d'), api.analysis(assetSymbol), api.risk(assetSymbol), api.financials(assetSymbol), api.sentiment(assetSymbol), api.newsImpact(assetSymbol)]).then((results) => { if (!ok) return; const [q, h, a, r, f, s, n] = results; if (q.status === 'fulfilled') setQuote(q.value); else console.error('Failed to load quote', q.reason); if (h.status === 'fulfilled') setHistory(h.value); else console.error('Failed to load history', h.reason); if (a.status === 'fulfilled') setAnalysis(a.value); else console.error('Failed to load analysis', a.reason); if (r.status === 'fulfilled') setRisk(r.value); else console.error('Failed to load risk', r.reason); if (f.status === 'fulfilled') setFinancials(f.value); else console.error('Failed to load financials', f.reason); if (s.status === 'fulfilled') setSentiment(s.value); else console.error('Failed to load sentiment', s.reason); if (n.status === 'fulfilled') setNews(n.value); else console.error('Failed to load news impact', n.reason); }).finally(() => ok && setLoading(false)); return () => { ok = false; }; }, [assetSymbol, range]);
  React.useEffect(() => { api.compare(compareSymbols).then(setCompare).catch((error) => console.error('Failed to load comparison', error)); }, [compareSymbols]);

  const selectedCategory = categories.find((category) => category.id === categoryId) ?? categories[0];
  const selectedAsset = selectedCategory?.assets.find((asset) => asset.symbol === assetSymbol) ?? selectedCategory?.assets[0];
  const changeCategory = (id: string) => { const next = categories.find((category) => category.id === id); setCategoryId(id); setAssetSymbol(next?.assets[0]?.symbol ?? assetSymbol); };
  const ask = () => api.ask(question, assetSymbol, language).then((payload: { answer: string }) => setAnswer(payload.answer)).catch((error) => console.error('Failed to ask assistant', error));
  const addHolding = () => setPortfolio((items) => [...items, newHolding]);

  return <main className="min-h-screen bg-terminal-bg text-terminal-text"><div className="mx-auto flex w-full max-w-7xl flex-col gap-4 px-4 py-4 sm:px-6 lg:px-8"><Header t={t} language={language} setLanguage={setLanguage} loading={loading} onAbout={() => setAboutOpen(true)} /><Nav labels={l} section={section} setSection={setSection} />{section === 'dashboard' && <section className="grid gap-4 lg:grid-cols-[268px_minmax(0,1fr)]"><aside className="space-y-4"><ControlPanel t={t} categories={categories} categoryId={categoryId} assetSymbol={assetSymbol} onCategoryChange={changeCategory} onAssetChange={setAssetSymbol} /><Watchlist t={t} categories={categories} selectedSymbol={assetSymbol} onSelect={setAssetSymbol} /></aside><div className="space-y-4"><PriceStrip t={t} quote={quote} asset={selectedAsset} /><div className="grid gap-4 xl:grid-cols-[minmax(0,1.25fr)_360px]"><div className="space-y-4"><ChiefInvestmentCard t={t} language={language} quote={quote} risk={risk} /><ChartPanel t={t} l={l} history={history} quote={quote} range={range} setRange={setRange} /></div><div className="space-y-4"><DataNotice t={t} quote={quote} history={history} /><SentimentPanel t={t} l={l} sentiment={sentiment} /><NewsPanel t={t} l={l} news={news} /></div></div><AICommittee t={t} language={language} quote={quote} risk={risk} financials={financials} /><div className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]"><FinancialPanel t={t} financials={financials} /><RiskPanel t={t} risk={risk} /></div></div></section>}{section === 'compare' && <CompareSection t={t} l={l} compare={compare} symbols={compareSymbols} setSymbols={setCompareSymbols} />}{section === 'assistant' && <AssistantSection l={l} question={question} setQuestion={setQuestion} answer={answer} ask={ask} />}{section === 'portfolio' && <PortfolioSection l={l} quote={quote} portfolio={portfolio} newHolding={newHolding} setNewHolding={setNewHolding} addHolding={addHolding} />}{section === 'calendar' && <CalendarSection l={l} language={language} calendar={calendar} />}{section === 'news' && <NewsPanel t={t} l={l} news={news} expanded />}<AboutDialog t={t} open={aboutOpen} onClose={() => setAboutOpen(false)} /><Footer t={t} /></div></main>;
}

function Header({ t, language, setLanguage, loading, onAbout }: { t: Translation; language: Language; setLanguage: (value: Language) => void; loading: boolean; onAbout: () => void }) { return <header className="flex flex-col gap-4 border-b border-terminal-border pb-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-3 text-terminal-cyan"><Sparkles size={20} /><span className="text-xs font-semibold uppercase tracking-[0.2em]">{t.eyebrow}</span></div><h1 className="mt-2 text-3xl font-semibold text-white sm:text-4xl">{t.appName}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-terminal-muted">{t.tagline}</p></div><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><LanguageSwitch t={t} language={language} setLanguage={setLanguage} /><button className="about-button" onClick={onAbout}><Info size={16} />{t.about}</button><div className="flex items-center gap-3 rounded-md border border-terminal-border bg-terminal-panel px-4 py-3 shadow-glow"><Activity className={loading ? 'animate-pulse text-terminal-amber' : 'text-terminal-green'} size={20} /><div><p className="text-xs text-terminal-muted">{t.systemStatus}</p><p className="text-sm font-semibold text-white">{loading ? t.refreshingData : t.marketDataReady}</p></div></div></div></header>; }
function Nav({ labels: l, section, setSection }: { labels: typeof labels.th; section: Section; setSection: (section: Section) => void }) { const items: Array<[Section, string]> = [['dashboard', l.dashboard], ['compare', l.compare], ['assistant', l.assistant], ['portfolio', l.portfolio], ['calendar', l.calendar], ['news', l.news]]; return <nav aria-label="Market Pulse sections" className="flex gap-2 overflow-auto rounded-md border border-terminal-border bg-terminal-panel p-2">{items.map(([id, label]) => <button key={id} aria-current={section === id ? 'page' : undefined} className={`watch-button min-w-fit px-4 ${section === id ? 'watch-button-active' : ''}`} onClick={() => setSection(id)}>{label}</button>)}</nav>; }
function LanguageSwitch({ t, language, setLanguage }: { t: Translation; language: Language; setLanguage: (value: Language) => void }) { return <div className="flex items-center gap-2 rounded-md border border-terminal-border bg-terminal-panel p-1"><Languages size={17} className="ml-2 text-terminal-muted" /><button className={`lang-button ${language === 'th' ? 'lang-button-active' : ''}`} onClick={() => setLanguage('th')}>{t.languageThai}</button><button className={`lang-button ${language === 'en' ? 'lang-button-active' : ''}`} onClick={() => setLanguage('en')}>{t.languageEnglish}</button></div>; }
function ControlPanel({ t, categories, categoryId, assetSymbol, onCategoryChange, onAssetChange }: { t: Translation; categories: AssetCategory[]; categoryId: string; assetSymbol: string; onCategoryChange: (id: string) => void; onAssetChange: (symbol: string) => void; }) { const assets = categories.find((category) => category.id === categoryId)?.assets ?? []; return <Panel title={t.assetConsole} icon={<WalletCards size={18} />}><label className="field-label">{t.category}</label><div className="select-shell"><select value={categoryId} onChange={(event) => onCategoryChange(event.target.value)}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><ChevronDown size={16} /></div><label className="field-label mt-4">{t.asset}</label><div className="select-shell"><select value={assetSymbol} onChange={(event) => onAssetChange(event.target.value)}>{assets.map((asset) => <option key={asset.symbol} value={asset.symbol}>{asset.label}</option>)}</select><ChevronDown size={16} /></div></Panel>; }
function Watchlist({ t, categories, selectedSymbol, onSelect }: { t: Translation; categories: AssetCategory[]; selectedSymbol: string; onSelect: (symbol: string) => void; }) { return <Panel title={t.watchlist} icon={<Radar size={18} />}><div className="max-h-[560px] space-y-3 overflow-auto pr-1">{categories.map((category) => <div key={category.id}><p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-terminal-muted">{category.name}</p><div className="grid grid-cols-2 gap-2">{category.assets.map((asset) => <button className={`watch-button ${asset.symbol === selectedSymbol ? 'watch-button-active' : ''}`} key={asset.symbol} onClick={() => onSelect(asset.symbol)}>{asset.label}</button>)}</div></div>)}</div></Panel>; }
function PriceStrip({ t, quote, asset }: { t: Translation; quote: AssetQuote | null; asset?: Asset }) { const positive = (quote?.change_percent ?? 0) >= 0; return <div className="grid gap-3 md:grid-cols-4"><MetricCard label={t.selectedAsset} value={asset?.label ?? quote?.symbol ?? t.loading} icon={<Globe2 size={18} />} /><MetricCard label={t.lastPrice} value={quote?.price == null ? 'Unavailable' : `${formatNumber(quote.price)} ${quote.currency ?? ''}`} icon={<BarChart3 size={18} />} /><MetricCard label={t.dailyChange} value={formatPercent(quote?.change_percent)} tone={positive ? 'green' : 'red'} icon={<LineChart size={18} />} /><MetricCard label={t.dataSource} value={quote?.source ?? 'Unavailable'} icon={<ShieldCheck size={18} />} /></div>; }
function MetricCard({ label, value, icon, tone }: { label: string; value: string; icon: React.ReactNode; tone?: 'green' | 'red' }) { return <div className="rounded-md border border-terminal-border bg-terminal-panel p-4"><div className="mb-3 flex items-center justify-between gap-3 text-terminal-muted">{icon}<span className="text-right text-xs uppercase tracking-[0.12em]">{label}</span></div><p className={`text-xl font-semibold ${tone === 'green' ? 'text-terminal-green' : tone === 'red' ? 'text-terminal-red' : 'text-white'}`}>{value}</p></div>; }
function DataNotice({ t, quote, history }: { t: Translation; quote: AssetQuote | null; history: AssetHistory | null }) { const metadata = quote?.metadata; return <Panel title={t.dataSource} icon={<Clock3 size={18} />}><p className="text-sm text-terminal-muted">{t.quoteSource}: {quote?.source ?? 'Unavailable'} | {t.historySource}: {history?.source ?? 'Unavailable'}</p><p className="mt-2 text-sm text-terminal-muted">{t.updatedAt}: {formatTime(metadata?.updated_at ?? quote?.timestamp)}</p><div className="mt-3 grid gap-2 text-xs text-terminal-muted sm:grid-cols-3"><span>Provider: {metadata?.provider ?? quote?.source ?? 'Unavailable'}</span><span>Confidence: {metadata?.confidence ?? 'low'}</span><span>Cache: {metadata?.cache_status ?? 'unavailable'}</span></div>{(quote?.data_warning || metadata?.data_warning) && <p className="mt-3 rounded-md border border-amber-300/30 bg-amber-300/10 p-2 text-sm text-amber-100">{quote?.data_warning ?? metadata?.data_warning}</p>}</Panel>; }
function ChartPanel({ t, l, history, quote, range, setRange }: { t: Translation; l: typeof labels.th; history: AssetHistory | null; quote: AssetQuote | null; range: string; setRange: (range: string) => void }) { const chartData = (history?.points ?? []).map((point) => ({ ...point, label: new Date(point.time).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) })); const hasData = chartData.length > 0; return <Panel title={t.priceChart} icon={<LineChart size={18} />}><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2">{ranges.map((item) => <button key={item} aria-pressed={range === item} className={`pill ${range === item ? 'watch-button-active' : ''}`} onClick={() => setRange(item)}>{item.toUpperCase()}</button>)}</div><span className="text-xs text-terminal-muted">{l.realData}</span></div><div className="mb-3 grid gap-2 text-xs text-terminal-muted sm:grid-cols-2"><span>{l.ohlc}: O {formatNumber(quote?.open)} H {formatNumber(quote?.high)} L {formatNumber(quote?.low)} C {formatNumber(quote?.price)}</span><span className="sm:text-right">{history?.points.length ?? 0} {t.points} | {history?.source ?? 'Unavailable'}</span></div><div className="mb-3 flex flex-wrap gap-2">{['EMA', 'RSI', 'MACD', t.volume].map((item) => <span className="pill" key={item}>{item}</span>)}</div><div className="h-[320px] w-full">{hasData ? <ResponsiveContainer><AreaChart data={chartData}><CartesianGrid stroke="#1e2b3f" strokeDasharray="3 3" /><XAxis dataKey="label" stroke="#7e8da8" tick={{ fontSize: 11 }} /><YAxis stroke="#7e8da8" tick={{ fontSize: 11 }} domain={['dataMin', 'dataMax']} /><Tooltip contentStyle={{ background: '#0a101c', border: '1px solid #1e2b3f', borderRadius: 6, color: '#d9e7ff' }} /><Area type="monotone" dataKey="close" stroke="#35d0ff" strokeWidth={2} fill="#35d0ff22" /></AreaChart></ResponsiveContainer> : <EmptyState message="Historical data unavailable." />}</div></Panel>; }
function ChiefInvestmentCard({ t, language, quote, risk }: { t: Translation; language: Language; quote: AssetQuote | null; risk: RiskResponse | null }) { const hasMarketData = quote?.price != null && quote?.change_percent != null; const change = quote?.change_percent ?? 0; const view = !hasMarketData ? 'Unavailable' : change > 1 ? t.bullish : change < -1 ? t.bearish : t.neutral; const summary = !hasMarketData ? (language === 'th' ? 'ข้อมูลยังไม่เพียงพอสำหรับการวิเคราะห์ที่น่าเชื่อถือ' : 'There is currently insufficient market data to produce a reliable analysis.') : language === 'th' ? `ภาพรวมของ ${quote?.symbol ?? 'สินทรัพย์นี้'} อยู่ในโซน${view} แต่ยังควรประเมินความผันผวนและสภาพคล่องควบคู่กัน` : `${quote?.symbol ?? 'This asset'} currently screens as ${view.toLowerCase()}, but volatility and liquidity should be reviewed together.`; return <Panel title={t.chiefInvestmentAI} icon={<BriefcaseBusiness size={18} />}><div className="grid gap-3 md:grid-cols-4"><StatusTile label={t.currentView} value={view} /><StatusTile label={t.confidence} value={hasMarketData ? t.medium : 'Low'} /><StatusTile label={t.riskScore} value={risk?.risk_score == null ? 'Unavailable' : `${risk.risk_score} / 10`} /><StatusTile label={t.volatility} value={risk?.volatility_level ?? t.loading} /></div><p className="mt-4 rounded-md bg-terminal-panel2 p-3 text-sm leading-6 text-white"><span className="font-semibold text-terminal-cyan">{t.aiSummary}: </span>{summary}</p></Panel>; }
function AICommittee({ t, language, quote, risk, financials }: { t: Translation; language: Language; quote: AssetQuote | null; risk: RiskResponse | null; financials: FinancialsResponse | null }) { const thai = language === 'th'; const cards = [t.technicalAnalyst, t.fundamentalAnalyst, t.macroEconomist, t.newsAnalyst, t.riskOfficer]; return <Panel title={t.aiCommittee} icon={<Brain size={18} />}><div className="grid gap-3 lg:grid-cols-5">{cards.map((title, index) => <div className="rounded-md border border-terminal-border bg-terminal-panel2 p-3" key={title}><h3 className="text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-terminal-muted">{thai ? ['ใช้ราคาและปริมาณซื้อขายจริงเมื่อพร้อมใช้งาน', financials?.applicable ? 'แสดงเฉพาะข้อมูลงบการเงินจริงที่ผู้ให้บริการส่งกลับ' : 'สินทรัพย์นี้ไม่มีงบการเงินบริษัท', 'ดอกเบี้ย เงินเฟ้อ และค่าเงินต้องใช้แหล่งข้อมูลจริง', 'ยังไม่ได้ตั้งค่าผู้ให้บริการข่าว', `คะแนนความเสี่ยง ${risk?.risk_score ?? 'ประเมินไม่ได้'}`][index] : ['Uses real price and volume when available.', financials?.applicable ? 'Only provider-returned financial statement data is shown.' : 'This asset does not publish corporate financial statements.', 'Rates, inflation, and FX require configured data sources.', 'No news provider configured.', `Risk score ${risk?.risk_score ?? 'unavailable'}`][index]}</p></div>)}</div></Panel>; }
function RiskPanel({ t, risk }: { t: Translation; risk: RiskResponse | null }) { return <Panel title={t.riskAnalysis} icon={<AlertTriangle size={18} />}><StatusRow label={t.volatility} value={risk?.volatility_level ?? t.loading} /><StatusRow label={t.riskScore} value={risk?.risk_score == null ? 'Unavailable' : `${risk.risk_score} / 10`} /><ListBlock title={t.mainRisk} items={risk?.main_risks} /><ListBlock title={t.actionPlan} items={risk?.risk_controls} /></Panel>; }
function FinancialPanel({ t, financials }: { t: Translation; financials: FinancialsResponse | null }) { if (!financials?.applicable) return <Panel title={t.financialStatements} icon={<Building2 size={18} />}><p className="text-sm leading-6 text-white">{financials?.message ?? t.notApplicable}</p></Panel>; const facts = financials.facts ?? {}; return <Panel title={t.financialStatements} icon={<Building2 size={18} />}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[[t.profitability, [[t.revenue, facts.revenue_trend], [t.profit, facts.net_profit_trend], [t.margins, facts.gross_margin]]], [t.financialHealth, [[t.debt, facts.debt_to_equity], [t.cashFlow, facts.cash_flow_quality]]], [t.valuation, [[t.pe, facts.pe], [t.pbv, facts.pbv], [t.dividend, facts.dividend_yield]]], [t.efficiency, [[t.roe, facts.roe], [t.roa, facts.roa], [t.eps, facts.eps]]]].map(([title, rows]) => <div className="rounded-md border border-terminal-border bg-terminal-panel2 p-3" key={String(title)}><h3 className="mb-3 text-sm font-semibold text-white">{String(title)}</h3>{(rows as Array<[string, unknown]>).map(([label, value]) => <StatusRow key={label} label={label} value={typeof value === 'number' ? formatNumber(value, 3) : String(value ?? 'Unavailable')} />)}</div>)}</div></Panel>; }
function SentimentPanel({ t, l, sentiment }: { t: Translation; l: typeof labels.th; sentiment: SentimentResponse | null }) { return <Panel title={t.marketSentiment} icon={<Scale size={18} />}><div className="flex items-center gap-4"><div className="sentiment-ring"><span>{sentiment?.score ?? 'N/A'}</span></div><div><p className="text-sm font-semibold text-white">{sentiment?.label ?? 'Unavailable'}</p><p className="mt-2 text-sm text-terminal-muted">{sentiment?.note ?? l.unavailableNote}</p></div></div></Panel>; }
function NewsPanel({ t, l, news, expanded = false }: { t: Translation; l: typeof labels.th; news: NewsImpactResponse | null; expanded?: boolean }) { const items = news?.items ?? []; return <Panel title={t.newsMonitor} icon={<Newspaper size={18} />}>{items.length ? items.map((item) => <div className="rounded-md bg-terminal-panel2 p-3" key={item.headline}><p className="text-sm font-semibold text-white">{item.headline}</p><div className="mt-3 grid gap-2 text-sm text-terminal-muted sm:grid-cols-3"><span>{t.source}: {item.source}</span><span>{l.impact}: {item.impact_level}</span><span>{l.sentiment}: {item.sentiment}</span></div><p className="mt-3 text-sm leading-6 text-terminal-text">{item.ai_explanation}</p>{expanded && <p className="mt-2 text-sm text-amber-100">{l.riskWarning}: {item.risk_warning}</p>}</div>) : <EmptyState message={news?.message ?? l.noData} />}<p className="mt-3 text-xs text-terminal-muted">{l.unavailableNote}</p></Panel>; }
function CompareSection({ t, l, compare, symbols, setSymbols }: { t: Translation; l: typeof labels.th; compare: CompareResponse | null; symbols: string[]; setSymbols: (symbols: string[]) => void }) { const hasPoints = (compare?.performance_points ?? []).length > 0; return <Panel title={l.comparison} icon={<BarChart3 size={18} />}><div className="mb-4 flex flex-wrap gap-2">{comparePresets.map((preset) => <button className={`watch-button px-4 ${preset.join(',') === symbols.join(',') ? 'watch-button-active' : ''}`} key={preset.join(',')} onClick={() => setSymbols(preset)}>{preset.join(' vs ')}</button>)}</div><div className="h-[300px]">{hasPoints ? <ResponsiveContainer><ReLineChart data={compare?.performance_points ?? []}><CartesianGrid stroke="#1e2b3f" strokeDasharray="3 3" /><XAxis dataKey="time" hide /><YAxis stroke="#7e8da8" /><Tooltip contentStyle={{ background: '#0a101c', border: '1px solid #1e2b3f', color: '#d9e7ff' }} />{symbols.map((symbol, index) => <Line key={symbol} type="monotone" dataKey={symbol} stroke={index === 0 ? '#35d0ff' : '#33d17a'} dot={false} />)}</ReLineChart></ResponsiveContainer> : <EmptyState message={l.noData} />}</div><div className="mt-4 overflow-auto"><table className="w-full text-left text-sm"><thead className="text-terminal-muted"><tr><th>Symbol</th><th>{t.lastPrice}</th><th>{t.dailyChange}</th><th>{t.volatility}</th><th>{t.riskScore}</th><th>Type</th></tr></thead><tbody>{compare?.items.map((item) => <tr className="border-t border-terminal-border" key={item.symbol}><td className="py-2 text-white">{item.symbol}</td><td>{formatNumber(item.price)} {item.currency}</td><td>{formatPercent(item.change_percent)}</td><td>{item.volatility_estimate}</td><td>{item.risk_score == null ? 'Unavailable' : `${item.risk_score}/10`}</td><td>{item.asset_type}</td></tr>)}</tbody></table></div><p className="mt-4 rounded-md bg-terminal-panel2 p-3 text-sm leading-6 text-white">{compare?.summary.th && (t === translations.th ? compare.summary.th : compare.summary.en)}</p></Panel>; }
function AssistantSection({ l, question, setQuestion, answer, ask }: { l: typeof labels.th; question: string; setQuestion: (q: string) => void; answer: string; ask: () => void }) { return <Panel title={l.assistant} icon={<Brain size={18} />}><textarea className="input-shell min-h-28" value={question} onChange={(event) => setQuestion(event.target.value)} aria-label={l.question} /><button className="about-button mt-3" onClick={ask}>{l.ask}</button>{answer && <p className="mt-4 rounded-md bg-terminal-panel2 p-4 text-sm leading-6 text-white">{answer}</p>}</Panel>; }
function PortfolioSection({ l, quote, portfolio, newHolding, setNewHolding, addHolding }: { l: typeof labels.th; quote: AssetQuote | null; portfolio: PortfolioHolding[]; newHolding: PortfolioHolding; setNewHolding: (h: PortfolioHolding) => void; addHolding: () => void }) { const values: Array<number | null> = portfolio.map((item) => item.symbol === quote?.symbol && quote?.price != null ? item.quantity * quote.price : null); const total = values.reduce<number>((sum, value) => sum + (value ?? 0), 0); return <Panel title={l.portfolio} icon={<WalletCards size={18} />}><div className="grid gap-3 md:grid-cols-5"><input aria-label="Symbol" className="input-shell" value={newHolding.symbol} onChange={(e) => setNewHolding({ ...newHolding, symbol: e.target.value.toUpperCase() })} /><input aria-label={l.quantity} className="input-shell" type="number" value={newHolding.quantity} onChange={(e) => setNewHolding({ ...newHolding, quantity: Number(e.target.value) })} /><input aria-label={l.averageCost} className="input-shell" type="number" value={newHolding.averageCost} onChange={(e) => setNewHolding({ ...newHolding, averageCost: Number(e.target.value) })} /><input aria-label="Currency" className="input-shell" value={newHolding.currency} onChange={(e) => setNewHolding({ ...newHolding, currency: e.target.value.toUpperCase() })} /><button className="about-button" disabled={!newHolding.symbol || newHolding.quantity <= 0 || newHolding.averageCost <= 0} onClick={addHolding}>{l.addHolding}</button></div><div className="mt-4 grid gap-3">{portfolio.length ? portfolio.map((item, index) => { const price = item.symbol === quote?.symbol ? quote?.price : null; const value = values[index]; return <div className="rounded-md bg-terminal-panel2 p-3" key={`${item.symbol}-${index}`}><div className="grid gap-2 md:grid-cols-5"><b>{item.symbol}</b><span>{l.quantity}: {item.quantity}</span><span>{l.currentValue}: {value == null ? 'Unavailable' : `${formatNumber(value)} ${item.currency}`}</span><span>{l.gainLoss}: {price == null ? 'Unavailable' : formatPercent(((price - item.averageCost) / item.averageCost) * 100)}</span><span>{l.allocation}: {total && value != null ? formatPercent((value / total) * 100) : 'Unavailable'}</span></div></div>; }) : <EmptyState message={l.noData} />}</div><p className="mt-4 text-sm text-terminal-muted">{l.aiComment}: {l.concentration} and volatility should be reviewed before adding exposure.</p></Panel>; }
function CalendarSection({ l, language, calendar }: { l: typeof labels.th; language: Language; calendar: CalendarResponse | null }) { const events = calendar?.events ?? []; return <Panel title={l.calendar} icon={<CalendarDays size={18} />}><div className="grid gap-3 md:grid-cols-2">{events.length ? events.map((event) => <div className="rounded-md bg-terminal-panel2 p-3" key={`${event.date}-${event.name}`}><p className="font-semibold text-white">{event.date} | {event.name}</p><p className="mt-2 text-sm text-terminal-muted">{event.region} | {l.impact}: {event.impact_level}</p><p className="mt-2 text-sm leading-6">{language === 'th' ? event.note_th : event.note_en}</p><p className="mt-2 text-xs text-terminal-cyan">{event.related_assets.join(', ')}</p></div>) : <EmptyState message={(language === 'th' ? calendar?.message_th : calendar?.message) ?? l.noData} />}</div><p className="mt-3 text-xs text-terminal-muted">{l.unavailableNote}</p></Panel>; }
function AboutDialog({ t, open, onClose }: { t: Translation; open: boolean; onClose: () => void }) { if (!open) return null; return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="about-dialog"><div className="mb-4 flex items-center justify-between border-b border-terminal-border pb-3"><h2 className="text-xl font-semibold text-white">Market Pulse AI</h2><button className="icon-button" onClick={onClose}><X size={18} /></button></div><p className="text-sm leading-6">{t.aboutSummary}</p><InfoRow label={t.version} value="0.1.0" /><InfoRow label={t.founder} value="Ponrat Saripan" /><InfoRow label={t.repository} value={repoUrl} href={repoUrl} /><InfoRow label={t.license} value="MIT License" /></div></div>; }
function InfoRow({ label, value, href }: { label: string; value: string; href?: string }) { return <div className="mt-3 flex flex-col gap-1 rounded-md bg-terminal-panel2 p-3 sm:flex-row sm:items-center sm:justify-between"><span className="text-xs uppercase tracking-[0.14em] text-terminal-muted">{label}</span>{href ? <a className="text-terminal-cyan" href={href} target="_blank" rel="noreferrer">{value}</a> : <span className="font-semibold text-white">{value}</span>}</div>; }
function Footer({ t }: { t: Translation }) { return <footer className="rounded-md border border-terminal-border bg-terminal-panel px-4 py-3 text-sm leading-6 text-terminal-muted"><div className="flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><p><span className="font-semibold text-white">{t.notFinancialAdvice}.</span> {t.disclaimerText}</p><div className="flex flex-wrap gap-3 text-terminal-cyan"><span>{t.createdBy}</span><span>{t.mitLicense}</span><a href={repoUrl} target="_blank" rel="noreferrer">GitHub</a></div></div></footer>; }
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-md border border-terminal-border bg-terminal-panel/95 p-4 shadow-glow"><div className="mb-4 flex items-center gap-2 border-b border-terminal-border pb-3 text-white">{icon}<h2 className="text-sm font-semibold uppercase tracking-[0.14em]">{title}</h2></div>{children}</section>; }
function StatusRow({ label, value }: { label: string; value: string }) { return <div className="mb-2 flex items-center justify-between gap-3 rounded-md bg-terminal-panel2 px-3 py-2"><span className="text-xs uppercase tracking-[0.12em] text-terminal-muted">{label}</span><span className="text-sm font-semibold text-white">{value}</span></div>; }
function StatusTile({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-terminal-panel2 p-3"><p className="text-xs uppercase tracking-[0.12em] text-terminal-muted">{label}</p><p className="mt-2 text-lg font-semibold text-terminal-amber">{value}</p></div>; }
function ListBlock({ title, items }: { title: string; items?: string[] }) { return <div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-terminal-muted">{title}</p><ul className="space-y-2">{(items ?? []).map((item) => <li className="rounded-md bg-terminal-panel2 px-3 py-2 text-sm leading-6 text-terminal-text" key={item}>{item}</li>)}</ul></div>; }
function EmptyState({ message }: { message: string }) { return <div className="flex h-full min-h-28 items-center justify-center rounded-md border border-dashed border-terminal-border bg-terminal-panel2 p-4 text-center text-sm text-terminal-muted">{message}</div>; }

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);

