export const en = {
  appName: 'Market Pulse AI', eyebrow: 'Professional Investment Dashboard', tagline: 'A professional asset intelligence dashboard with balanced, cautious AI views and transparent market data context.',
  languageThai: 'ไทย', languageEnglish: 'EN', systemStatus: 'System Status', refreshingData: 'Refreshing data', providerFallback: 'Provider fallback active', marketDataReady: 'Market data ready',
  assetConsole: 'Asset Console', category: 'Category', asset: 'Asset', watchlist: 'Watchlist', selectedAsset: 'Selected Asset', lastPrice: 'Last Price', dailyChange: 'Daily Change', dataSource: 'Data Source', quoteSource: 'Quote Source', historySource: 'History Source', providerNotice: 'Provider Notice', updatedAt: 'Updated At', priceChart: 'Price Chart', points: 'points',
  aiCommittee: 'AI Investment Committee', chiefInvestmentAI: 'Chief Investment AI', currentView: 'Current View', bullish: 'Bullish', neutral: 'Neutral', bearish: 'Bearish', confidence: 'Confidence', low: 'Low', medium: 'Medium', high: 'High', riskScore: 'Risk Score', mainOpportunity: 'Main Opportunity', mainRisk: 'Main Risk', aiSummary: 'AI Summary',
  technicalAnalyst: 'Technical Analyst', fundamentalAnalyst: 'Fundamental Analyst', macroEconomist: 'Macro Economist', newsAnalyst: 'News Analyst', riskOfficer: 'Risk Officer',
  trend: 'Trend', rsi: 'RSI', macd: 'MACD', ema: 'EMA', volume: 'Volume', chartStructure: 'Chart Structure', revenue: 'Revenue', profit: 'Profit', cashFlow: 'Cash Flow', debt: 'Debt', roe: 'ROE', roa: 'ROA', valuation: 'Valuation', interestRates: 'Interest Rates', inflation: 'Inflation', dxy: 'DXY', oil: 'Oil', gold: 'Gold', bondYield: 'Bond Yield', newsSentiment: 'News Sentiment', headlineRisk: 'Headline Risk', industryEvents: 'Industry Events', earningsEvents: 'Earnings Events', portfolioRisk: 'Portfolio Risk', volatility: 'Volatility', drawdown: 'Drawdown', concentrationRisk: 'Concentration Risk', liquidityRisk: 'Liquidity Risk',
  aiAnalysis: 'AI Analysis', riskAnalysis: 'Risk Analysis', financialStatements: 'Financial Statements', newsMonitor: 'News Monitor', facts: 'Facts', interpretation: 'Interpretation', bullishFactors: 'Bullish Factors', bearishFactors: 'Bearish Factors', support: 'Support', resistance: 'Resistance', invalidation: 'Invalidation', actionPlan: 'Action Plan', disclaimer: 'Disclaimer',
  profitability: 'Profitability', margins: 'Margins', growth: 'Growth', financialHealth: 'Financial Health', liquidity: 'Liquidity', pe: 'P/E', pbv: 'P/BV', dividend: 'Dividend', efficiency: 'Efficiency', eps: 'EPS', notApplicable: 'Financial statement analysis is not applicable to this asset type', alternativeFundamentals: 'Alternative fundamentals to monitor',
  headline: 'Headline', source: 'Source', impact: 'Impact', expectedMarketImpact: 'Expected Market Impact', fearGreed: 'Fear & Greed', marketSentiment: 'Market Sentiment', cryptoSentiment: 'Crypto sentiment', stockSentiment: 'Stock market sentiment', loading: 'Loading', noData: 'No data', notFinancialAdvice: 'This is not financial advice', disclaimerText: 'This dashboard is for education and research only. Verify market data independently and define a risk plan before making investment decisions.'
} as const;
