export const th = {
  appName: 'Market Pulse AI', eyebrow: 'Powered by PIA™', tagline: 'ผู้ช่วยการลงทุนส่วนตัวสำหรับเริ่มต้นวัน วิเคราะห์อย่างระมัดระวัง และแสดงที่มาของข้อมูลอย่างโปร่งใส',
  languageThai: 'ไทย', languageEnglish: 'EN', systemStatus: 'สถานะระบบ', refreshingData: 'กำลังอัปเดตข้อมูล', providerFallback: 'ใช้ข้อมูลสำรองบางส่วน', marketDataReady: 'ข้อมูลตลาดพร้อมใช้งาน',
  assetConsole: 'ศูนย์เลือกสินทรัพย์', category: 'หมวดสินทรัพย์', asset: 'สินทรัพย์', watchlist: 'รายการติดตาม', selectedAsset: 'สินทรัพย์ที่เลือก', lastPrice: 'ราคาล่าสุด', dailyChange: 'เปลี่ยนแปลงรายวัน', dataSource: 'แหล่งข้อมูล', quoteSource: 'แหล่งข้อมูลราคา', historySource: 'แหล่งข้อมูลกราฟ', providerNotice: 'หมายเหตุจากผู้ให้บริการ', updatedAt: 'อัปเดตล่าสุด', priceChart: 'กราฟราคา', points: 'จุดข้อมูล',
  aiCommittee: 'คณะกรรมการลงทุน AI', chiefInvestmentAI: 'Chief Investment AI', currentView: 'มุมมองปัจจุบัน', bullish: 'เชิงบวก', neutral: 'เป็นกลาง', bearish: 'เชิงลบ', confidence: 'ความเชื่อมั่น', low: 'ต่ำ', medium: 'ปานกลาง', high: 'สูง', riskScore: 'คะแนนความเสี่ยง', mainOpportunity: 'โอกาสหลัก', mainRisk: 'ความเสี่ยงหลัก', aiSummary: 'สรุปโดย AI',
  technicalAnalyst: 'นักวิเคราะห์เทคนิค', fundamentalAnalyst: 'นักวิเคราะห์ปัจจัยพื้นฐาน', macroEconomist: 'นักเศรษฐศาสตร์มหภาค', newsAnalyst: 'นักวิเคราะห์ข่าว', riskOfficer: 'เจ้าหน้าที่บริหารความเสี่ยง',
  trend: 'แนวโน้ม', rsi: 'RSI', macd: 'MACD', ema: 'EMA', volume: 'ปริมาณซื้อขาย', chartStructure: 'โครงสร้างกราฟ', revenue: 'รายได้', profit: 'กำไร', cashFlow: 'กระแสเงินสด', debt: 'หนี้สิน', roe: 'ROE', roa: 'ROA', valuation: 'มูลค่าเหมาะสม', interestRates: 'อัตราดอกเบี้ย', inflation: 'เงินเฟ้อ', dxy: 'DXY', oil: 'น้ำมัน', gold: 'ทองคำ', bondYield: 'อัตราผลตอบแทนพันธบัตร', newsSentiment: 'บรรยากาศข่าว', headlineRisk: 'ความเสี่ยงจากข่าว', industryEvents: 'เหตุการณ์อุตสาหกรรม', earningsEvents: 'ผลประกอบการ', portfolioRisk: 'ความเสี่ยงพอร์ต', volatility: 'ความผันผวน', drawdown: 'การย่อตัว', concentrationRisk: 'ความเสี่ยงจากการกระจุกตัว', liquidityRisk: 'ความเสี่ยงสภาพคล่อง',
  aiAnalysis: 'บทวิเคราะห์ AI', riskAnalysis: 'การประเมินความเสี่ยง', financialStatements: 'วิเคราะห์งบการเงิน', newsMonitor: 'ข่าวสำคัญ', facts: 'ข้อเท็จจริง', interpretation: 'การตีความ', bullishFactors: 'ปัจจัยบวก', bearishFactors: 'ปัจจัยลบ', support: 'แนวรับ', resistance: 'แนวต้าน', invalidation: 'เงื่อนไขที่ทำให้มุมมองเปลี่ยน', actionPlan: 'แผนรับมือ', disclaimer: 'คำเตือน',
  profitability: 'ความสามารถทำกำไร', margins: 'อัตรากำไร', growth: 'การเติบโต', financialHealth: 'ฐานะการเงิน', liquidity: 'สภาพคล่อง', pe: 'P/E', pbv: 'P/BV', dividend: 'เงินปันผล', efficiency: 'ประสิทธิภาพ', eps: 'EPS', notApplicable: 'การวิเคราะห์งบการเงินไม่เหมาะกับสินทรัพย์ประเภทนี้', alternativeFundamentals: 'ปัจจัยพื้นฐานที่ควรติดตามแทน',
  headline: 'หัวข้อข่าว', source: 'แหล่งข่าว', impact: 'ผลกระทบ', expectedMarketImpact: 'ผลกระทบที่คาดต่อราคา', fearGreed: 'Fear & Greed', marketSentiment: 'ภาวะตลาด', cryptoSentiment: 'อารมณ์ตลาดคริปโต', stockSentiment: 'บรรยากาศตลาดหุ้น', loading: 'กำลังโหลด', noData: 'ไม่มีข้อมูล', notFinancialAdvice: 'นี่ไม่ใช่คำแนะนำทางการเงิน', disclaimerText: 'ข้อมูลนี้จัดทำเพื่อการศึกษาและการวิเคราะห์เบื้องต้น ผู้ลงทุนควรตรวจสอบข้อมูลจากแหล่งทางการและกำหนดแผนบริหารความเสี่ยงก่อนตัดสินใจลงทุน', about: 'เกี่ยวกับ', version: 'เวอร์ชัน', founder: 'ผู้ก่อตั้ง', repository: 'Repository', license: 'สัญญาอนุญาต', createdBy: 'Created by Ponrat Saripan', mitLicense: 'MIT License', aboutSummary: 'Market Pulse AI เป็นโครงการโอเพนซอร์สสำหรับการวิจัยการลงทุนที่เน้นความโปร่งใส ความระมัดระวัง และการเข้าถึงสองภาษา'
} as const;

